branches:
  only:
    - dev
    - master

image: Visual Studio 2019

clone_folder: c:\projects\gerber_x2

matrix:
    fast_finish: true

platform:
  - x64

configuration:
  - Release

#  .\CGAL-5.0.2-Setup.exe /S /D=C:\dev\CGAL-5.0
# https://cgal.geometryfactory.com/CGAL/precompiled_libs/auxiliary/x64/GMP/5.0.1/gmp-all-CGAL-3.9.zip
# https://cgal.geometryfactory.com/CGAL/precompiled_libs/auxiliary/x64/MPFR/3.0.0/mpfr-all-CGAL-3.9.zip
# qmake -config release
#new-item -itemtype symboliclink -path C:\Libraries -name boost_1_71_0 -value C:\local\boost_1_71_0
install:
  - ps: Start-FileDownload 'https://github.com/CGAL/cgal/releases/download/releases%2FCGAL-5.0/CGAL-5.0-library.zip'
  - ps: Start-FileDownload 'https://cgal.geometryfactory.com/CGAL/precompiled_libs/auxiliary/x64/GMP/5.0.1/gmp-all-CGAL-3.9.zip'
  - ps: Start-FileDownload 'https://cgal.geometryfactory.com/CGAL/precompiled_libs/auxiliary/x64/MPFR/3.0.0/mpfr-all-CGAL-3.9.zip'
  - ps: 7z x CGAL-5.0-library.zip -oC:\dev -y
  - ps: 7z x gmp-all-CGAL-3.9.zip -oC:\dev\CGAL-5.0\auxiliary\gmp
  - ps: 7z x mpfr-all-CGAL-3.9.zip -oC:\dev\CGAL-5.0\auxiliary\gmp
  - ps: mkdir C:\local
  - ps: new-item -itemtype symboliclink -path C:\local -name boost_1_71_0 -value C:\Libraries\boost_1_71_0
  - set QTDIR=C:\Qt\5.14.2\msvc2017_64
  - set PATH=%PATH%;%QTDIR%\bin
  - call "C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Auxiliary\Build\vcvars64.bat" x64

build_script:
    - mkdir bin
    - cd G2G
    - qmake -config release
    - nmake